export const languages = {
  Africano: 'af',
  Basco: 'eu',
  Búlgaro: 'bg',
  Catalão: 'ca',
  'Árabe (Egito)': 'ar-EG',
  'Árabe (Jordânia)': 'ar-JO',
  'Árabe (Kuwait)': 'ar-KW',
  'Árabe (Líbano)': 'ar-LB',
  'Árabe (Catar)': 'ar-QA',
  'Árabe (Emirados Árabes Unidos)': 'ar-AE',
  'Árabe (Marrocos)': 'ar-MA',
  'Árabe (Iraque)': 'ar-IQ',
  'Árabe (Argélia)': 'ar-DZ',
  'Árabe (Bahrain)': 'ar-BH',
  'Árabe (Líbia)': 'ar-LY',
  'Árabe (OmaOmãn)': 'ar-OM',
  'Árabe (Arábia Saudita)': 'ar-SA',
  'Árabe (Tunísia)': 'ar-TN',
  'Árabe (Iémen)': 'ar-YE',
  Tcheco: 'cs',
  Holandês: 'nl-NL',
  'Inglês (Australia)': 'en-AU',
  'Inglês (Canada)': 'en-CA',
  'Inglês (India)': 'en-IN',
  'Inglês (New Zealand)': 'en-NZ',
  'Inglês (South Africa)': 'en-ZA',
  'Inglês (UK)': 'en-GB',
  'Inglês (US)': 'en-US',
  Finlandês: 'fi',
  Francês: 'fr-FR',
  Galego: 'gl',
  Alemão: 'de-DE',
  Grego: 'el-GR',
  Hebraico: 'he',
  Húngaro: 'hu',
  Islandês: 'is',
  Italiano: 'it-IT',
  Indonésio: 'id',
  Japonês: 'ja',
  Coreano: 'ko',
  Latino: 'la',
  Chinês: 'zh-CN',
  Taiwanês: 'zh-TW',
  Cantones: 'zh-HK',
  Malaio: 'ms-MY',
  Norueguês: 'no-NO',
  Polonês: 'pl',
  Português: 'pt - PT',
  'Português (Brasil)': 'pt-br',
  Romeno: 'ro-RO',
  Russo: 'ru',
  Sérvio: 'sr-SP',
  Eslovaco: 'sk',
  'Espanhol (Argentina)': 'es-AR',
  'Espanhol (Bolívia)': 'es-BO',
  'Espanhol (Chile)': 'es-CL',
  'Espanhol (Colômbia)': 'es-CO',
  'Espanhol (Costa Rica)': 'es-CR',
  'Espanhol (República Dominicana)': 'es-DO',
  'Espanhol (Equador)': 'es-EC',
  'Espanhol (El Salvador)': 'es-SV',
  'Espanhol (Guatemala)': 'es-GT',
  'Espanhol (Honduras)': 'es-HN',
  'Espanhol (México)': 'es-MX',
  'Espanhol (Nicarágua)': 'es-NI',
  'Espanhol (Panamá)': 'es-PA',
  'Espanhol (Paraguai)': 'es-PY',
  'Espanhol (Perú)': 'es-PE',
  'Espanhol (Porto Rico)': 'es-PR',
  'Espanhol (Espanha)': 'es-ES',
  'Espanhol (US)': 'es-US',
  'Espanhol (Uruguai)': 'es-UY',
  'Espanhol (Venezuela)': 'es-VE',
  Sueca: 'sv-SE',
  Turco: 'tr',
  Zulu: 'zu',
};
